### PR TITLE
Pull payment fixes

### LINKED ISSUE #3490: Go back button at confirm lightning payout has no function
**Describe the bug**
Go back button at confirm lightning payout has no function

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Go to Payouts
2. Click on a confirmed or waiting for approval payout an select action send resp. + approval
3. At sending page, go back button has no function

**Expected behavior**

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   v1.4.6.0 
- Deployment Method:      lunanode  
- Browser:                 Safari 

**Logs (if applicable)**

**Setup Parameters**

**Additional context**

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes #3490 plus a redirect and missing store context for Lightning payouts.

Note: Is there a reason for `UILightningLikePayoutController` to sit in `BTCPayServer/Data/Payouts/LightningLike` instead of the controllers directory?

### CODE REVIEW

File: BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs [hunk 1]
```diff
@@ -21,7 +21,7 @@
 
 namespace BTCPayServer.Data.Payouts.LightningLike
 {
-    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
+    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
```
Comment (Kukks) [inline BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs:24]: This is incorrect, as the ln payouts page shows payouts from multiple stores

**Review by Kukks — CHANGES_REQUESTED** [review]

File: BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs (hunk 1 above)
Comment (dennisreimann) [reply BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs]: Thanks, updated in [42ddd21](https://github.com/btcpayserver/btcpayserver/pull/3497/commits/42ddd2153d04ef441d58fb03087eb04cc5f92a41).

**Review by Kukks — APPROVED** [review]
