### PR TITLE
Fix bug with top-up invoices when used with "Only enable the payment method after user explicitly chooses it" enabled

### LINKED ISSUE #2772: Topup invoice shows LN in the checkout -when `Only enable the payment method after user explicitly chooses it` is enabled
**Describe the bug**
For some reason, LN shows up as a payment method for a top-up invoice, but once you select it disapperas. However, it provides error n the invoice logs.

**To Reproduce the bug**

Steps to reproduce the reported bug:
1. Make sure you're on 1.2.0 and have LN enabled
2. Make sure to enable `Only enable the payment method after user explicitly chooses it` (This is critical to enable to be able to replicate)
3. Create an invoice without an amount
4. Go to the checkout, you'll see LN as the option
5. Choose LN from the drop-down, nothing happens

**Expected behavior**

LN Shouldn't appear as a payment method option for toupup invoices.

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.2.0   
- Deployment Method:   Docker, using clightning     

**Logs (if applicable)**

The invoice logs are as a result spammed

Date | Message
-- | --
12/08/2021 19:00:43 | Creation of invoice starting
12/08/2021 19:00:43 | BTC_USD: The rating rule is coingecko(BTC_USD)
12/08/2021 19:00:43 | BTC_USD: The evaluated rating rule is 44089.639
12/08/2021 19:00:43 | BTC (On-Chain): Payment method details creation took 1 milliseconds
12/08/2021 19:00:43 | BTC (Off-Chain): Payment method details creation took 0 milliseconds
12/08/2021 19:00:43 | Saving invoice took 260 milliseconds
12/08/2021 19:00:43 | Invoice W1smhpJQ42aDMBh1PULYWA new event: invoice_created (1001)
12/08/2021 19:00:45 | BTC: Activating
12/08/2021 19:00:45 | BTC (On-Chain): Payjoin is enabled for this invoice.
12/08/2021 19:00:52 | BTC_LightningLike: Activating
12/08/2021 19:00:52 | BTC_LightningLike: Payment method unavailable (Impossible to create lightning invoice (msatoshi: should be positive msat or 'any': invalid token '0'))
12/08/2021 19:00:52 | BTC_LightningLike: Activating
12/08/2021 19:00:52 | BTC_LightningLike: Payment method unavailable (Impossible to create lightning invoice (msatoshi: should be positive msat or 'any': invalid token '0'))
12/08/2021 19:00:52

**Setup Parameters**

**Additional context**

### PR DESCRIPTION
**Pull request by bolatovumar**
close #2772

### CODE REVIEW

File: BTCPayServer/Controllers/InvoiceController.cs [hunk 1]
```diff
@@ -348,8 +345,8 @@ private Task WhenAllFetched(InvoiceLogs logs, Dictionary<CurrencyPair, Task<Rate
                 var logPrefix = $"{supportedPaymentMethod.PaymentId.ToPrettyString()}:";
                 var storeBlob = store.GetStoreBlob();
 
-                object preparePayment;
-                if (storeBlob.LazyPaymentMethods)
+                object? preparePayment;
+                if (storeBlob.LazyPaymentMethods && entity.Type != InvoiceType.TopUp)
```
Comment (bolatovumar) [inline BTCPayServer/Controllers/InvoiceController.cs:349]: This is the actual fix, the rest is just me specifying that certain values can be `null`.

File: BTCPayServer/Controllers/InvoiceController.cs [hunk 2]
```diff
@@ -1,6 +1,6 @@
+#nullable enable
 using System;
 using System.Collections.Generic;
-using System.ComponentModel.DataAnnotations;
```
Comment (bolatovumar) [inline BTCPayServer/Controllers/InvoiceController.cs:3]: Unused directives.

**Review by Kukks — CHANGES_REQUESTED** [review]
I don't think this is correct. It completely removes compatibility of Topup invoices + Lazy Payments. The fix needs to happen in the LightningLikePaymentHandler somehow.

**Comment by bolatovumar** [comment]
@Kukks alright, I updated it in https://github.com/btcpayserver/btcpayserver/pull/2780/commits/5fa520708c0828970d059395d64a58199f406705 to check in `LightningLikePaymentHandler`. Not sure if it's entirely the right approach.

File: BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs [hunk 3]
```diff
@@ -51,9 +52,13 @@ public class LightningLikePaymentHandler : PaymentMethodHandlerBase<LightningSup
 
         public override async Task<IPaymentMethodDetails> CreatePaymentMethodDetails(
             InvoiceLogs logs,
-            LightningSupportedPaymentMethod supportedPaymentMethod, PaymentMethod paymentMethod, StoreData store,
+            LightningSupportedPaymentMethod supportedPaymentMethod, PaymentMethod paymentMethod, Data.StoreData store,
```
Comment (bolatovumar) [inline BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs:55]: Had to update this to `Data.StoreData` because now `StoreData` is an ambiguous reference as there is also a `StoreData` in `BTCPayServer.Client.Models`.

File: BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs [hunk 4]
```diff
@@ -11,7 +12,7 @@
 using BTCPayServer.Logging;
 using BTCPayServer.Models;
 using BTCPayServer.Models.InvoicingModels;
-using BTCPayServer.Rating;
+using BTCPayServer.Client.Models;
```
Comment (bolatovumar) [inline BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs:15]: Replaced unused `BTCPayServer.Rating` with `BTCPayServer.Client.Models` which has the `InvoiceType` enum.

**Review by Kukks — APPROVED** [review]
ACK
