### PR TITLE
LNURL: Add missing CORS

### LINKED ISSUE #4615: [Bug]: CORS-related - snort.social still doesn't play with our lnaddress implementation
### What is your BTCPay version?

 v1.7.6+ed0ccd6f1

### How did you deploy BTCPay Server?

Docker

### What happened?

grafik

### How did you encounter this bug?

1. Add lnaddress to my nostr account
2. click on address in profile, 500 sats and Zap
3. "Failed to load invoice" appears + JS console output from above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox 109

### Additional information

my public nostr profile on snort if you wanna try:
https://snort.social/p/npub1l2q2pyyjlt5qsgwnmk3ga0dme2aafj35j25fk878p58uzanyfcsqqzlgc2

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by dennisreimann**
In addition to #4587. Closes #4615.

### CODE REVIEW

File: BTCPayServer/Controllers/UILNURLController.cs [hunk 1]
```diff
@@ -81,7 +81,6 @@ public class UILNURLController : Controller
             _btcPayNetworkJsonSerializerSettings = btcPayNetworkJsonSerializerSettings;
         }
 
-
```
Comment (Kukks) [inline BTCPayServer/Controllers/UILNURLController.cs:84]: We should it Cors here too?

**Review by Kukks — CHANGES_REQUESTED** [review]

File: BTCPayServer/Controllers/UILNURLController.cs (hunk 1 above)
Comment (dennisreimann) [reply BTCPayServer/Controllers/UILNURLController.cs:84]: Not sure about the use case. @petzsch Do you know where it can be relevant for Pull Payment + LNURL withdrawal?

Comment (petzsch) [reply BTCPayServer/Controllers/UILNURLController.cs:84]: When you click on my lnaddress (the little bolt symbol is infront of it here): https://snort.social/p/npub1l2q2pyyjlt5qsgwnmk3ga0dme2aafj35j25fk878p58uzanyfcsqqzlgc2

you get a dialog where you can chose an amount and create an invoice for the lightning address... would be super lit to get it working.

Comment (dennisreimann) [reply BTCPayServer/Controllers/UILNURLController.cs:84]: Yes, I fixed that. Kukks and my question now is if you can imagine a use case to add CORS for Pull Payment + LNURL withdrawal as well — If so, we'd also add that.

Comment (petzsch) [reply BTCPayServer/Controllers/UILNURLController.cs:84]: OK, I don't currently see a need for it. At least not in conjunction with ln-address as such payment methods are afaik not specified for it.

If someone wants to create or claim pull payments via JavaScript from a remote site, he might as well use our API for that (and a proper programing language). So I think we are good here.

Comment (dennisreimann) [reply BTCPayServer/Controllers/UILNURLController.cs:84]: Agreed :+1:
