### PR TITLE
BIP21 + LNURL fix

### LINKED ISSUE #4609: [Bug]: Invalid LNURL created for top-up invoices in new checkout
### What is your BTCPay version?

v1.7.6+ed0ccd6f1 

### How did you deploy BTCPay Server?

Docker

### What happened?

Breez and many other wallets can't scan the combined QR code including the LNURL for my top-up invoices.

### How did you encounter this bug?

I scanned a top-up invoice QR code, it failed in Breez, I reported the bug to breez and they tested it with all sorts of wallets with the same outcome.

### Relevant log output

```shell
Parsing the LNURL with https://lightningdecoder.com/ gives:
JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

### What browser do you use?

Firefox 109

### Additional information

could this be related to the CORS change introduced in this version?
For testing, create a fresh invoice [here](https://otr.4sats.net/?email=markus@petzsch.eu).

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by dennisreimann**
In case of the unified invoice, the LNURL wasn't correct — with this change we are simply reusing th one that was issued on invoice creation instead of generating it anew on the fly.

Also fixes missing uppercasing for the QR code in case of non-unified QR. And removes the `lightning:` scheme from the LNURL that's displayed to the user (unifies it with what we do for Onchain and Lightning)

Fixes #4609.

### CODE REVIEW

File: BTCPayServer/Payments/LNURLPay/LNURLPayPaymentHandler.cs [hunk 1]
```diff
@@ -107,12 +109,13 @@ public override IEnumerable<PaymentMethodId> GetSupportedPaymentMethods()
...
             var paymentMethodId = paymentMethod.GetId();
-            var cryptoInfo = invoiceResponse.CryptoInfo.First(o => o.GetpaymentMethodId() == paymentMethodId);
             var network = _networkProvider.GetNetwork<BTCPayNetwork>(model.CryptoCode);
+            var cryptoInfo = invoiceResponse.CryptoInfo.First(o => o.GetpaymentMethodId() == paymentMethodId);
+            var lnurl = cryptoInfo.PaymentUrls?.AdditionalData["LNURLP"].ToObject<string>();
             model.PaymentMethodName = GetPaymentMethodName(network);
-            model.InvoiceBitcoinUrl = cryptoInfo.PaymentUrls?.AdditionalData["LNURLP"].ToObject<string>();
-            model.InvoiceBitcoinUrlQR = model.InvoiceBitcoinUrl;
-            model.BtcAddress = model.InvoiceBitcoinUrl;
+            model.BtcAddress = lnurl?.Replace(UriScheme, "");
```
Comment (Kukks) [inline BTCPayServer/Payments/LNURLPay/LNURLPayPaymentHandler.cs:116]: We cant do this.  LNURL has bech32 mode, where this would work (`lnurl1...`), but the newer uri scheme would mean the protocol identifier would be cut off. (`lnurlp://`)

Comment (dennisreimann) [reply BTCPayServer/Payments/LNURLPay/LNURLPayPaymentHandler.cs:116]: That `UriScheme` is a [const defined as `lightning:`](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Payments/LNURLPay/LNURLPayPaymentHandler.cs#L44), so we should be good here.
