### PR TITLE
Show iframe when showing invoice in Shopify plugin

### LINKED ISSUE #4105: [Bug]: Invoice display broken on Shopify
### What is your BTCPay version?

BTCPay Server: v1.6.3.0 (on Umbrel)
Store: https://robotechy.com/

### How did you deploy BTCPay Server?

Umbrel Raspberry Pi docker image.

### What happened?

We have our Umbrel node server the JS file over HTTPS as per https://jorijn.com/installing-nginx-reverse-proxy-with-ssl-certificate-umbrel-btcpayserver/. I noticed that the JS file was failing to load for two reasons, (1) our SSL had expired, and (2) the URL to the JS file has been changed. The JS file is now loading (after updating the link), and we see the "Pay with BTCPay" icon again. However, when you click on it, it just has "Displaying Invoice..." but nothing actually pops up.

### How did you encounter this bug?

1. Go to https://robotechy.com
2. Go through to the checkout for an item (feel free to enter "BTCPayServer" and will tell son to ignore order).
3. Choose "BTCPay Server" method.
4. Click on "Pay with BTCPay".

### Relevant log output

_No response_

### What browser do you use?

Browser(s): Edge and Chrome

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by bolatovumar**
For whatever reason we do not call `btcpay.showFrame` after `btcpay.showInvoice` in the Shopify plugin even though we do it in other places. This results in the iframe being added to the document but not shown.

See here and here:

https://github.com/btcpayserver/btcpayserver/blob/5bbaa48b492556df32aaa8cd81b7e7ac9ea33794/BTCPayServer/wwwroot/payment-request/app.js#L131-L132

https://github.com/btcpayserver/btcpayserver/blob/4d0f76f9e8cf85c4104f248d5877d15dbc844a39/BTCPayServer/wwwroot/crowdfund/app.js#L222-L223

Close #4105

### CODE REVIEW

File: BTCPayServer/wwwroot/shopify/btcpay-shopify.js [hunk 1]
```diff
@@ -133,6 +133,7 @@ window.BTCPayShopifyIntegrationModule = function () {
                 });
             });
             window.btcpay.showInvoice(currentInvoiceData.invoiceId);
+            window.btcpay.showFrame();
```
Comment (bolatovumar) [inline BTCPayServer/wwwroot/shopify/btcpay-shopify.js:136]: Idk if there is an actual reason we weren't calling `showFrame` here previously or if it's just an oversight.

**Comment by bolatovumar** [comment]
Failing test unrelated

Capture

**Comment by Kukks** [comment]
Do you think we need to add this directly to the modal js instead of specifically here for shopify?

**Comment by bolatovumar** [comment]
> Do you think we need to add this directly to the modal js instead of specifically here for shopify?

@Kukks done in https://github.com/btcpayserver/btcpayserver/pull/4106/commits/66d7ad84c933ef9b13f57380ed1083835d341421

Looks like we can't just wholesale replace the old method with the new one because there is actually an alternative way to show the iframe by doing a `postMessage` which will end up showing/hiding the invoice as appropriate so I just created the method which can be used in other places.

File: BTCPayServer/wwwroot/modal/btcpay.js [hunk 2]
```diff
@@ -133,7 +138,9 @@
     window.btcpay = {
         showFrame: showFrame,
         hideFrame: hideFrame,
-        showInvoice: showInvoice,
+        showInvoice: appendInvoiceFrame,
```
Comment (bolatovumar) [inline BTCPayServer/wwwroot/modal/btcpay.js:141]: I kept the old global method name around in case there is someone who relies on it? If we don't care about it then it can just be deleted.

**Comment by NicolasDorier** [comment]
I let @Kukks decided whether to merge this PR, I don't know much about shopify

File: BTCPayServer/wwwroot/modal/btcpay.js (hunk 2 above)
Comment (Kukks) [reply BTCPayServer/wwwroot/modal/btcpay.js:141]: This is good, we should strive to always be backwards compatible
