### PR TITLE
QR scanner: Properly handle BIP21 input

### LINKED ISSUE #6665: [Bug]: QR Code Scanner in Bitcoin Send dialog should remove "BITCOIN:" prefix pefore putting it in the destination field
### What is your BTCPay version?

BTCPay Server v2.1.0+b09b61251 

### How did you deploy BTCPay Server?

docker

### What happened?

I scanned the BTC onchain deposit address of my Breez wallet via QR Code.

The content of the QR code is "BITCOIN:BC1...."

After scanning the BITCOIN:BC1 line got put in the destination field, however when trying to submit this transaction it's marked as invalid:

Image

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox on Win11

### Additional information

_No response_

### Are you sure this is a bug report?

- [x] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes #6665. Supersedes and closes #6672.

Details [here](https://github.com/btcpayserver/btcpayserver/pull/6672#issuecomment-2809299548)

### CODE REVIEW

File: BTCPayServer/wwwroot/js/wallet/wallet-camera-scanner.js [hunk 1]
```diff
@@ -1,15 +1,28 @@
 window.addEventListener("load", () => {
-    let $input = null;
+    let outputIndex = null;
     initCameraScanningApp("Scan address or payment link", data => {
-        if (data.includes('?') || $input == null) {
+        const bip21 = data.match(/bitcoin:(\w+)(?:\?(.*))?/)
```
Comment (NicolasDorier) [inline BTCPayServer/wwwroot/js/wallet/wallet-camera-scanner.js:4]: In petzsch screenshot, `bitcoin:` is capitalized to `BITCOIN:`

Comment (dennisreimann) [inline BTCPayServer/wwwroot/js/wallet/wallet-camera-scanner.js:4]:
```suggestion
        const bip21 = data.match(/bitcoin:(\w+)(?:\?(.*))?/i)
```
