### PR TITLE
set username on email change

### LINKED ISSUE #673: username stays the same after changing email
After I update email, username stays the same. And this is means to login I should use old email. 

**Your environment**
* `53cecc8c8a41033a88594b14521d3699f1a42d32`

**To Reproduce**
1. Go to `/Manage/Index`
2. Change email and confirm
3. Follow link in the email
4. New email used for password reset and notifications, but to actually login I still need to use the old one, as it actually not a email, but username on the login page

**Expected behavior**
username should be changed to the new email too

**Actual behavior**
username stays the same, and this is means I still need to use old details to login

### PR DESCRIPTION
**Pull request by Kukks**
closes #673

### CODE REVIEW

File: BTCPayServer/Controllers/ManageController.cs [hunk 1]
```diff
@@ -111,6 +111,7 @@ public async Task<IActionResult> Index(IndexViewModel model)
                 var setEmailResult = await _userManager.SetEmailAsync(user, model.Email);
                 if (!setEmailResult.Succeeded)
                 {
+                    await _userManager.SetUserNameAsync(user, model.Username);
```
Comment (NicolasDorier) [inline BTCPayServer/Controllers/ManageController.cs]: I don't think you want to put this line here. Probably after, if it succeeded
