### PR TITLE
Prevent an NRE in LNURL

### LINKED ISSUE #4904: Error scanning Print Only POS Scan QR code since v1.9.1 upgrade.
### What is your BTCPay version?

BTCPay Server v1.9.1

### How did you deploy BTCPay Server?

Manual deploy

### What happened?

When using Print only option in POS app, scanning the QR causes error in WoZ and Zeus apps.

### How did you encounter this bug?

Choose "Print Display" option in POS app, SAVE and then VIEW, try scan QR code presented.

### Relevant log output

_No response_

### What browser do you use?

Brave

### Additional information

Error regarding decoding QR code.

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by dennisreimann**
In addition to f05a7f9f14e0a2f906c79951a15311085774db85. Fixes #4904.

### CODE REVIEW

**Review by Kukks — APPROVED** [review]

File: BTCPayServer/Controllers/UILNURLController.cs [hunk 1]
```diff
@@ -468,9 +468,10 @@ public async Task<IActionResult> ResolveLightningAddress(string username)
             lnUrlMetadata ??= new Dictionary<string, string>();
 
             var pm = i.GetPaymentMethod(pmi);
-            var paymentMethodDetails = (LNURLPayPaymentMethodDetails)pm.GetPaymentMethodDetails();
+            var paymentMethodDetails = pm?.GetPaymentMethodDetails() as LNURLPayPaymentMethodDetails;
```
Comment (NicolasDorier) [inline BTCPayServer/Controllers/UILNURLController.cs:471]: I don't understand why this one can be null.

Comment (dennisreimann) [reply BTCPayServer/Controllers/UILNURLController.cs:471]: Me neither. I could not reproduce it in dev unfortunately, so no debugger — I can reproduce it on prod though, that's where I got the line that was causing it and I figured from your recent commit, that this might be a way to prevent it.

**Comment by NicolasDorier** [comment]
Ok so I will merge this as is just fixing the NRE.
