### PR TITLE
Fix pay button CSP issue when using modal

### LINKED ISSUE #2864: When Use Modal is selected in paybutton wizard, we have a CSP issue error
Despite this, the rest seems to work properly, it only crashes the preview.
Bug introduced by the new CSP rule: https://github.com/btcpayserver/btcpayserver/pull/2863

image

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes #2864.

### CODE REVIEW

File: BTCPayServer/wwwroot/paybutton/paybutton.js [hunk 1]
```diff
@@ -115,12 +93,10 @@ function inputChanges(event, buttonSize) {
     }
     
     var html =
-        //Scripts
-        (srvModel.useModal? getScripts(srvModel) :"") +
         // Styles
         getStyles('template-paybutton-styles') + (isSlider ? getStyles('template-slider-styles') : '') +
         // Form
-        '<form method="POST" '+ ( srvModel.useModal? ' onsubmit="onBTCPayFormSubmit(event);return false" ' : '' )+' action="' + esc(srvModel.urlRoot) + actionUrl + '" class="btcpay-form btcpay-form--' + (srvModel.fitButtonInline ? 'inline' : 'block') +'">\n' +
+        '<form method="POST" '+ ( srvModel.useModal? ' ' : '' )+' id="btcpay-paybutton-form" action="' + esc(srvModel.urlRoot) + actionUrl + '" class="btcpay-form btcpay-form--' + (srvModel.fitButtonInline ? 'inline' : 'block') +'">\n' +
```
Comment (NicolasDorier) [inline BTCPayServer/wwwroot/paybutton/paybutton.js:99]: It is a problem for people who have several button on a page.
We can just allow this particular event handler in the page instead with `unsafe-hashes` and `sha256-`.

I can refactor a bit myself to do this. (will edit your PR)

**Comment by NicolasDorier** [comment]
Take a look at my commit. I also improved a bit the taghelpers.

This we we can add the handler explicitely in the cshtml.

File: BTCPayServer/wwwroot/paybutton/paybutton.js (hunk 1 above)
Comment (dennisreimann) [reply BTCPayServer/wwwroot/paybutton/paybutton.js]: Good point! Had to make a slight adjustment in 1c7ce60, because otherwise it got called on submit regardless of the modal being used or not.
