### PR TITLE
Fix clipboard copy edge case

### LINKED ISSUE #3291: [Bug] Copy to clipboard doesn't work on receive address in Brave if HTTP (with domain other than localhost)
I host BTCPAY on rockpro64, 1.3.7.

If I click on the Copy button in the Wallet/Receive, it doesn't work.
However, the copy work on the checkout invoice.

### PR DESCRIPTION
**Pull request by dennisreimann**
Closes #3291.

### CODE REVIEW

File: BTCPayServer/wwwroot/js/copy-to-clipboard.js [hunk 1]
```diff
@@ -1,19 +1,35 @@
...
+        copyEl.style.position = 'absolute';
+        copyEl.style.opacity = '0';
+        copyEl.value = data;
+        document.body.appendChild(copyEl);
+        copyEl.select();
+        document.execCommand('copy');
+        copyEl.remove();
+        confirmCopy(confirm, message);
     }
+    item.blur();
```
Comment (NicolasDorier) [inline BTCPayServer/wwwroot/js/copy-to-clipboard.js:32]: should blur really be here??

Comment (dennisreimann) [reply BTCPayServer/wwwroot/js/copy-to-clipboard.js:32]: Yes, otherwise the button or link stays focused and keeps the highlighted styles.
