### PR TITLE
Checkout: Fix language select width in modal

### LINKED ISSUE #4820: [Bug]: Language Selector on Modal (light theme) is barely visible
### What is your BTCPay version?

v.1.8.4

### How did you deploy BTCPay Server?

Docker

### What happened?

grafik

grafik

### How did you encounter this bug?

see above

### Relevant log output

```shell
none
```

### What browser do you use?

Firefox

### Additional information

none

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by dennisreimann**
Initially delays the width calculation to the next render frame, so that the page is safely rendered. Closes #4820.

grafik

### CODE REVIEW

File: BTCPayServer/wwwroot/checkout-v2/checkout.js [hunk 1]
```diff
@@ -224,7 +224,7 @@ function initApp() {
             if (this.isProcessing) {
                 this.listenForConfirmations();
             }
-            updateLanguageSelect();
+            window.requestAnimationFrame(updateLanguageSelect);
```
Comment (Kukks) [inline BTCPayServer/wwwroot/checkout-v2/checkout.js:227]: Shouldnt we use Vue's nextTick instead? https://vuejs.org/api/general.html#nexttick

**Review by Kukks — CHANGES_REQUESTED** [review]

File: BTCPayServer/wwwroot/checkout-v2/checkout.js (hunk 1 above)
Comment (dennisreimann) [reply BTCPayServer/wwwroot/checkout-v2/checkout.js]: @kukks I think they amount to the same outcome, but I found a better way to solve it in [11ea96b](https://github.com/btcpayserver/btcpayserver/pull/4823/commits/11ea96b3982fdbd03c4bab14b2eb70fe2da778b4). There we should use the native DOM API there, because it's not in the Vue context.
