### PR TITLE
Retain store ids when filtering invoices

### LINKED ISSUE #1029: Filtering Store invoice - drop-down filter ignores storeid
**Describe the problem/bug**
If you filter invoices from a particular store, it will show invoices from `all` stores.

**Your environment**
* Version of BTCPay Server: v1.0.3.130
* Deployment method: Docker
* Other relevant environment details: Attempted on https://mainnet.demo.btcpayserver.org

**Logs (if applicable)**
Basic logs can be found in Server Settings > Logs.

**To Reproduce**
1. Go to Stores (make sure you have more than 1 store with paid invoice)
2. Click "Invoices" for a particular store (filters invoices by store)
3. From a drop-down menu select paid invoices.
4. See error -filter ignores store ID and filters for all stores

**Expected behavior**
If invoices are filtered by store, it should continue to filter by store even with a drop-down menu.

**Screenshots**

### PR DESCRIPTION
**Pull request by bolatovumar**
fix #1029

### CODE REVIEW

**Comment by bolatovumar** [comment]
Not sure if this is done the right way but seems to work. The reason store ids are stored in an array is because you could search by multiple store ids.

File: BTCPayServer/Models/InvoicingModels/InvoicesModel.cs [hunk 1]
```diff
@@ -13,9 +13,9 @@ public class InvoicesModel
         public int Total { get; set; }
         public string SearchTerm { get; set; }
         public int? TimezoneOffset { get; set; }
-
         public List<InvoiceModel> Invoices { get; set; } = new List<InvoiceModel>();
         public string StatusMessage { get; set; }
+        public string[] StoreIds { get; set; }
```
Comment (Kukks) [inline BTCPayServer/Models/InvoicingModels/InvoicesModel.cs]: The `SearchTerm` field handles ALL the filters. If you add ` storeid: xxx` it would filter on it. `storeid:xxx storeid:yyy` filters on multiple stores btw

File: BTCPayServer/Controllers/InvoiceController.UI.cs [hunk 2]
```diff
@@ -398,12 +398,16 @@ public async Task<IActionResult> UpdateCustomer(string invoiceId, [FromBody]Upda
         [BitpayAPIConstraint(false)]
         public async Task<IActionResult> ListInvoices(string searchTerm = null, int skip = 0, int count = 50, int timezoneOffset = 0)
         {
+            var fs = new SearchString(searchTerm);
```
Comment (Kukks) [inline BTCPayServer/Controllers/InvoiceController.UI.cs]: searchTerm is enough

File: BTCPayServer/Views/Invoice/ListInvoices.cshtml [hunk 3]
```diff
@@ -73,17 +73,25 @@
                                 <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                     <span class="sr-only">Toggle Dropdown</span>
                                 </button>
+
+                                @{
```
Comment (Kukks) [inline BTCPayServer/Views/Invoice/ListInvoices.cshtml]: You need to add a space in front of `storeIds`  using the ascii value (`%20`)

**Comment by NicolasDorier** [comment]
Ping @Kukks did @bolatovumar replied to your concerns?

**Comment by Kukks** [comment]
I think I can simplify this a bit, will play with it tomorrow

**Comment by NicolasDorier** [comment]
Ping @Kukks again :p

**Comment by NicolasDorier** [comment]
hey @bolatovumar you need to rebase this one and ping kukks to review again.

**Comment by bolatovumar** [comment]
@NicolasDorier alright, rebased. Ping @Kukks.

**Comment by pavlenex** [comment]
tACK. This seems to work now from the user perspective. I'll leave the code review to Kukks since he had some simplification in mind, but on the front-end it works as expected.
