### PR TITLE
Fix null reference error when "destinations" field is not specified or empty when creating a new wallet transaction

### LINKED ISSUE #3537: 500 error when making a POST request to create a new wallet transaction
**Describe the bug**

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Try to make a POST request to `"~/api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}/wallet/transactions"` with an empty request body
2. Notice you get a 500 error

Capture

**Expected behavior**

Expect to get an error message explaining what I need to specify in the request body.

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version: 1.4.7.0

### PR DESCRIPTION
**Pull request by bolatovumar**
fix #3537

### CODE REVIEW

**Review by Kukks — APPROVED** [review]

File: BTCPayServer/Controllers/GreenField/GreenfieldStoreOnChainWalletsController.cs [hunk 1]
```diff
@@ -282,6 +282,16 @@ public async Task<IActionResult> GetOnChainWalletUTXOs(string storeId, string cr
                 return this.CreateAPIError(503, "not-available", $"You need to allow non-admins to use hotwallets for their stores (in /server/policies)");
             }
 
+            if (request.Destinations == null || !request.Destinations.Any())
```
Comment (Kukks) [inline BTCPayServer/Controllers/GreenField/GreenfieldStoreOnChainWalletsController.cs:285]:
```suggestion
            if (request.Destinations?.Any() is not true)
```
