### PR TITLE
fix no store error message for payment request 

### LINKED ISSUE #628: Pay Request "No store" error consistent with warring in apps
We should make the error message consistent with the one in apps as it gives the user a link and exact action on what to do when no store is created.

Add a link to store /stores.

### PR DESCRIPTION
**Pull request by Kukks**
closes #628

### CODE REVIEW

File: BTCPayServer/Controllers/PaymentRequestController.cs [hunk 1]
```diff
@@ -98,7 +98,12 @@ public async Task<IActionResult> EditPaymentRequest(string id, string statusMess
                 return RedirectToAction("GetPaymentRequests",
                     new
                     {
-                        StatusMessage = "Error: You need to create at least one store before creating a payment request"
+                        StatusMessage = new StatusMessageModel()
```
Comment (pavlenex) [inline BTCPayServer/Controllers/PaymentRequestController.cs]: Can you please make the error message itself consistent with the one [here](https://github.com/btcpayserver/btcpayserver/pull/630/commits/40efdf01099ab21dddfa3b7e6506df59fbea3e9f)? 

Consistency in error message would help us with troubleshooting and documenting stuff.

Comment (Kukks) [reply BTCPayServer/Controllers/PaymentRequestController.cs]: done
