### PR TITLE
Fix bug with LN payment method API endpoint throwing 500

### LINKED ISSUE #2566: /api/v1/stores/{storeId}/payment-methods/LightningNetwork endpoint throws 500 error for stores with internal LN node
**Describe the bug**
If you try to hit the `/api/v1/stores/{storeId}/payment-methods/LightningNetwork` endpoint on a store with an internal LN node you will get a 500 error

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Make a `GET` request to a `/api/v1/stores/{storeId}/payment-methods/LightningNetwork` endpoint
2. Observe that you get a 500 error

**Expected behavior**

Should not get a 500 error.

**Screenshots**

Screen Shot 2021-06-13 at 6 58 54 PM

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:  1.1.2.0
- Deployment Method:   Docker
- Browser:  any client

### PR DESCRIPTION
**Pull request by bolatovumar**
close #2566

### CODE REVIEW

File: BTCPayServer/Controllers/GreenField/StoreLightningNetworkPaymentMethodsController.cs [hunk 1]
```diff
@@ -56,8 +56,12 @@ public class StoreLightningNetworkPaymentMethodsController : ControllerBase
                 .Where((method) => method.PaymentId.PaymentType == PaymentTypes.LightningLike)
                 .OfType<LightningSupportedPaymentMethod>()
                 .Select(paymentMethod =>
-                    new LightningNetworkPaymentMethodData(paymentMethod.PaymentId.CryptoCode,
-                        paymentMethod.GetExternalLightningUrl().ToString(), !excludedPaymentMethods.Match(paymentMethod.PaymentId)))
+                    new LightningNetworkPaymentMethodData(
+                        paymentMethod.PaymentId.CryptoCode,
+                        paymentMethod.GetExternalLightningUrl()?.ToString() ?? paymentMethod.GetDisplayableConnectionString(),
```
Comment (bolatovumar) [inline BTCPayServer/Controllers/GreenField/StoreLightningNetworkPaymentMethodsController.cs:61]: This line is the main change. Previously it could result in a 500 because `GetExternalLightningUrl` can return `null`.

File: BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs [hunk 2]
```diff
@@ -1,24 +1,23 @@
...
         [JsonIgnore]
         public PaymentMethodId PaymentId => new PaymentMethodId(CryptoCode, PaymentTypes.LightningLike);
 
         [Obsolete("Use Get/SetLightningUrl")]
         [JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
-        public string LightningConnectionString { get; set; }
+        public string? LightningConnectionString { get; set; }
 
-        public LightningConnectionString GetExternalLightningUrl()
+        public LightningConnectionString? GetExternalLightningUrl()
```
Comment (bolatovumar) [inline BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs:20]: Marked this and other things as nullable for more type safety.

File: BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs [hunk 3]
```diff
@@ -1,24 +1,23 @@
...
 using Newtonsoft.Json;
-using Newtonsoft.Json.Linq;
 
 namespace BTCPayServer.Payments.Lightning
 {
     public class LightningSupportedPaymentMethod : ISupportedPaymentMethod
     {
         public const string InternalNode = "Internal Node";
-        public string CryptoCode { get; set; }
+        public string? CryptoCode { get; set; }
```
Comment (NicolasDorier) [inline BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs:11]: are you sure it can be null? Maybe the way we initialize it, but this should not happen.

Comment (bolatovumar) [reply BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs:11]: @NicolasDorier C# says it can be `null` because it's not initialized with any value so it complains.

Comment (Kukks) [reply BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs:11]: Yeah #nullable will complain about most things but it's ok (I think you could do a flag that tells the compiler that it is NOT null though.. in typescript it was something like adding `!` )

**Review by Kukks — APPROVED** [review]
ACK

**Comment by NicolasDorier** [comment]
if it's not nullable, but we say it is, it is even worse than if we said ntohgin, will change this.
