### PR TITLE
Fix null reference exception when going to LN node settings before it's been set-up

### LINKED ISSUE #3407: 1.4.3: System.NullReferenceException when accessing Lightning Settings
**Describe the bug**
When accessing LN settings right after server installation and setup I get error 500 and System.NullReferenceException message in logs.

**To Reproduce the bug**
Steps to reproduce the reported bug:
1. Setup BTCPay with postgres and LND internal node
2. Sign up
3. Create a store named "Test"
4. Setup hot wallet
5. Attempt to setup LN node by going to https://example.com/btcpay-rt/stores/<STORE_ID>/lightning/BTC/settings
6. See error

These steps are also mostly represented by [this script](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/blob/master/tests/multi-package/btcpayserver-regtest/selenium_after_install.py) just with the URL modified to contain `/settings`. Note that even going back to URL without `/settings` and clicking settings in the UI results in same error 500.

**Expected behavior**

LN setup page shows without error

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:   1.4.3
- Deployment Method:        Debian package
- Browser:                  Chromium

**Logs (if applicable)**

Probably relevant part:

```
Feb 03 16:25:35 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJ1", Request id "0HMF755IP8AJ1:00000002": An unhandled exception was thrown by the application.
Feb 03 16:25:35 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:25:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:25:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:25:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 99
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
```

<details>
<summary>Full log</summary>

```
Feb 03 16:23:17 disp6572 systemd[1]: Started A cross platform, self-hosted server compatible with Bitpay API.
Feb 03 16:23:18 disp6572 btcpayserver[7499]: info: Configuration:  Data Directory: /var/lib/btcpayserver-system-regtest/.btcpayserver/RegTest
Feb 03 16:23:18 disp6572 btcpayserver[7499]: info: Configuration:  Configuration File: /etc/btcpayserver-system-regtest/btcpayserver.conf
Feb 03 16:23:18 disp6572 btcpayserver[7499]: info: Configuration:  Network: Regtest
Feb 03 16:23:18 disp6572 btcpayserver[7499]: info: Configuration:  LogFile: /var/log/btcpayserver-system-regtest/debug.log
Feb 03 16:23:18 disp6572 btcpayserver[7499]: info: Configuration:  Log Level: Debug
Feb 03 16:23:19 disp6572 btcpayserver[7499]: info: BTCPayServer.Plugins.PluginManager: Loading plugins from /var/lib/btcpayserver-system-regtest/.btcpayserver/Plugins
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.4.3.0
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.4.3.0
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: Configuration:  Supported chains: BTC
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: Configuration:  BTC: Explorer url is http://127.0.0.1:24447/
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: Configuration:  BTC: Cookie file is /var/lib/nbxplorer-regtest/RegTest/.cookie
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: Configuration:  Network: Regtest
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: Configuration:  LogFile: /var/log/btcpayserver-system-regtest/debug.log
Feb 03 16:23:20 disp6572 btcpayserver[7499]: info: Configuration:  Log Level: Debug
Feb 03 16:23:27 disp6572 btcpayserver[7499]: info: Configuration:  Root Path: /btcpay-rt
Feb 03 16:23:27 disp6572 btcpayserver[7499]: info: PayServer:      Starting listening NBXplorer (BTC)
Feb 03 16:23:28 disp6572 btcpayserver[7499]: info: PayServer:      Start watching invoices
Feb 03 16:23:28 disp6572 btcpayserver[7499]: info: PayServer:      Starting payment request expiration watcher
Feb 03 16:23:28 disp6572 btcpayserver[7499]: info: PayServer:      0 pending payment requests being checked since last run
Feb 03 16:23:28 disp6572 btcpayserver[7499]: info: PayServer:      Importing 0 invoices into the search table in 0 pages
Feb 03 16:23:28 disp6572 btcpayserver[7499]: info: PayServer:      Full invoice search import successful
Feb 03 16:23:28 disp6572 btcpayserver[7499]: info: Configuration:  Now listening on: http://127.0.0.1:23002
Feb 03 16:23:52 disp6572 systemd[1]: Stopping A cross platform, self-hosted server compatible with Bitpay API...
Feb 03 16:23:52 disp6572 btcpayserver[7499]: info: PayServer:      DelayedTransactionBroadcasterHostedService successfully exited...
Feb 03 16:23:52 disp6572 btcpayserver[7499]: info: PayServer:      TorServices successfully exited...
Feb 03 16:23:52 disp6572 btcpayserver[7499]: info: PayServer:      CheckConfigurationHostedService successfully exited...
Feb 03 16:23:52 disp6572 btcpayserver[7499]: info: PayServer:      PullPaymentHostedService successfully exited...
Feb 03 16:23:57 disp6572 btcpayserver[7499]: info: PayServer:      NBXplorerListener successfully exited...
Feb 03 16:23:57 disp6572 btcpayserver[7499]: info: PayServer:      LightningListener successfully exited...
Feb 03 16:23:57 disp6572 btcpayserver[7499]: info: PayServer:      Stop watching invoices
Feb 03 16:23:57 disp6572 btcpayserver[7499]: info: PayServer:      RatesHostedService successfully exited...
Feb 03 16:23:57 disp6572 btcpayserver[7499]: info: PayServer:      DynamicDnsHostedService successfully exited...
Feb 03 16:23:57 disp6572 btcpayserver[7499]: info: PayServer:      NewVersionCheckerHostedService successfully exited...
Feb 03 16:23:57 disp6572 btcpayserver[7499]: info: PayServer:      DbMigrationsHostedService successfully exited...
Feb 03 16:23:57 disp6572 systemd[1]: btcpayserver-system-regtest.service: Main process exited, code=exited, status=143/n/a
Feb 03 16:23:57 disp6572 systemd[1]: btcpayserver-system-regtest.service: Failed with result 'exit-code'.
Feb 03 16:23:57 disp6572 systemd[1]: Stopped A cross platform, self-hosted server compatible with Bitpay API.
Feb 03 16:23:57 disp6572 systemd[1]: Starting A cross platform, self-hosted server compatible with Bitpay API...
Feb 03 16:23:57 disp6572 systemd[1]: Started A cross platform, self-hosted server compatible with Bitpay API.
Feb 03 16:23:58 disp6572 btcpayserver[9585]: info: Configuration:  Data Directory: /var/lib/btcpayserver-system-regtest/.btcpayserver/RegTest
Feb 03 16:23:58 disp6572 btcpayserver[9585]: info: Configuration:  Configuration File: /etc/btcpayserver-system-regtest/btcpayserver.conf
Feb 03 16:23:58 disp6572 btcpayserver[9585]: info: Configuration:  Network: Regtest
Feb 03 16:23:58 disp6572 btcpayserver[9585]: info: Configuration:  LogFile: /var/log/btcpayserver-system-regtest/debug.log
Feb 03 16:23:58 disp6572 btcpayserver[9585]: info: Configuration:  Log Level: Debug
Feb 03 16:23:59 disp6572 btcpayserver[9585]: info: BTCPayServer.Plugins.PluginManager: Loading plugins from /var/lib/btcpayserver-system-regtest/.btcpayserver/Plugins
Feb 03 16:24:00 disp6572 btcpayserver[9585]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.4.3.0
Feb 03 16:24:00 disp6572 btcpayserver[9585]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.4.3.0
Feb 03 16:24:00 disp6572 btcpayserver[9585]: info: Configuration:  Supported chains: BTC
Feb 03 16:24:01 disp6572 btcpayserver[9585]: info: Configuration:  BTC: Explorer url is http://127.0.0.1:24447/
Feb 03 16:24:01 disp6572 btcpayserver[9585]: info: Configuration:  BTC: Cookie file is /var/lib/nbxplorer-regtest/RegTest/.cookie
Feb 03 16:24:01 disp6572 btcpayserver[9585]: info: Configuration:  Network: Regtest
Feb 03 16:24:01 disp6572 btcpayserver[9585]: info: Configuration:  LogFile: /var/log/btcpayserver-system-regtest/debug.log
Feb 03 16:24:01 disp6572 btcpayserver[9585]: info: Configuration:  Log Level: Debug
Feb 03 16:24:07 disp6572 btcpayserver[9585]: info: Configuration:  Root Path: /btcpay-rt
Feb 03 16:24:08 disp6572 btcpayserver[9585]: info: PayServer:      Starting listening NBXplorer (BTC)
Feb 03 16:24:08 disp6572 btcpayserver[9585]: info: PayServer:      Start watching invoices
Feb 03 16:24:08 disp6572 btcpayserver[9585]: info: PayServer:      Starting payment request expiration watcher
Feb 03 16:24:09 disp6572 btcpayserver[9585]: info: Configuration:  Now listening on: http://127.0.0.1:23002
Feb 03 16:24:09 disp6572 btcpayserver[9585]: info: PayServer:      Importing 0 invoices into the search table in 0 pages
Feb 03 16:24:09 disp6572 btcpayserver[9585]: info: PayServer:      Full invoice search import successful
Feb 03 16:24:09 disp6572 btcpayserver[9585]: info: PayServer:      0 pending payment requests being checked since last run
Feb 03 16:25:19 disp6572 btcpayserver[9585]: info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
Feb 03 16:25:19 disp6572 btcpayserver[9585]: info: PayServer:      BTC: 0 payments happened while offline
Feb 03 16:25:19 disp6572 btcpayserver[9585]: info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
Feb 03 16:25:29 disp6572 btcpayserver[9585]: info: PayServer:      First admin created, disabling subscription (disable-registration is set to true)
Feb 03 16:25:29 disp6572 btcpayserver[9585]: info: PayServer:      A new user just registered admin@example.com (admin)
Feb 03 16:25:35 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJ1", Request id "0HMF755IP8AJ1:00000002": An unhandled exception was thrown by the application.
Feb 03 16:25:35 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:25:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:25:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:25:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 99
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:25:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:25:44 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJ2", Request id "0HMF755IP8AJ2:00000002": An unhandled exception was thrown by the application.
Feb 03 16:25:44 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:25:44 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:25:44 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:25:44 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 99
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:25:44 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:25:54 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJ5", Request id "0HMF755IP8AJ5:00000002": An unhandled exception was thrown by the application.
Feb 03 16:25:54 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:25:54 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:25:54 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:25:54 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 99
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:25:54 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:26:00 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJ6", Request id "0HMF755IP8AJ6:00000002": An unhandled exception was thrown by the application.
Feb 03 16:26:00 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:26:00 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:26:00 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:26:00 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 99
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:26:00 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:26:02 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJ7", Request id "0HMF755IP8AJ7:00000002": An unhandled exception was thrown by the application.
Feb 03 16:26:02 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:26:02 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:26:02 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:26:02 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 99
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:26:02 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:26:06 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJC", Request id "0HMF755IP8AJC:00000002": An unhandled exception was thrown by the application.
Feb 03 16:26:06 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:26:06 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:26:06 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:26:06 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 100
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:26:06 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:27:30 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJD", Request id "0HMF755IP8AJD:00000002": An unhandled exception was thrown by the application.
Feb 03 16:27:30 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:27:30 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:27:30 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:27:30 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 100
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:27:30 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:27:35 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJG", Request id "0HMF755IP8AJG:00000002": An unhandled exception was thrown by the application.
Feb 03 16:27:35 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:27:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:27:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:27:35 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 100
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:27:35 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Feb 03 16:32:53 disp6572 btcpayserver[9585]: fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMF755IP8AJJ", Request id "0HMF755IP8AJJ:00000002": An unhandled exception was thrown by the application.
Feb 03 16:32:53 disp6572 btcpayserver[9585]: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at BTCPayServer.Controllers.UIStoresController.LightningSettings(String storeId, String cryptoCode) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 209
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 03 16:32:53 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
Feb 03 16:32:53 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Feb 03 16:32:53 disp6572 btcpayserver[9585]: --- End of stack trace from previous location ---
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 100
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/cadr-build/btcpayserver-1.4.3/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
Feb 03 16:32:53 disp6572 btcpayserver[9585]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

</details>

**Setup Parameters**

```
btc.explorer.cookiefile=/var/lib/nbxplorer-regtest/RegTest/.cookie

btc.explorer.url=http://127.0.0.1:24447

debuglog=/var/log/btcpayserver-system-regtest/debug.log

dockerdeployment=false

network=regtest

port=23002

btc.lightning=type=lnd-rest;server=https://127.0.0.1:9092/;macaroonfilepath=/var/lib/lnd-system-regtest/invoice/invoice+readonly.macaroon;certthumbprint=C5CE8F1541393C9CD3285E704B070B94401C7BB979333CA2F6F1B6FD7D5343D1

rootPath=/btcpay-rt
postgres=User ID=btcpayserversystemregtest;Password=weWqjoEMhDBP;Host=localhost;Port=;Database=btcpayserversystemregtest;
```

### PR DESCRIPTION
**Pull request by bolatovumar**
fix #3407

### CODE REVIEW

File: BTCPayServer/Controllers/UIStoresController.LightningLike.cs [hunk 1]
```diff
@@ -102,16 +103,16 @@ public async Task<IActionResult> SetupLightningNode(string storeId, LightningNod
 
             vm.CanUseInternalNode = await CanUseInternalLightning();
 
-            var network = vm.CryptoCode == null ? null : _ExplorerProvider.GetNetwork(vm.CryptoCode);
```
Comment (bolatovumar) [inline BTCPayServer/Controllers/UIStoresController.LightningLike.cs:105]: No need for this indirection, we can just check if `CryptoCode ` is `null` and if it's not, we know we are good. This also helps the compiler understand that `vm.CryptoCode` is not `null` down below when we use it so it doesn't complain that it can be `null`.

File: BTCPayServer/Controllers/UIStoresController.LightningLike.cs [hunk 2]
```diff
@@ -218,8 +226,7 @@ public async Task<IActionResult> LightningSettings(string storeId, string crypto
             };
             await SetExistingValues(store, vm);
 
-            var lnSet = lightning != null;
```
Comment (bolatovumar) [inline BTCPayServer/Controllers/UIStoresController.LightningLike.cs:221]: We don't need an extra variable here, we can just do a null check directly. It also helps the compiler to understand that `lightning` is not `null` down below when we use it.

File: BTCPayServer/Controllers/UIStoresController.LightningLike.cs [hunk 3]
```diff
@@ -315,10 +323,10 @@ public async Task<IActionResult> SetLightningNodeEnabled(string storeId, string
             if (store == null)
                 return NotFound();
 
-            var network = cryptoCode == null ? null : _ExplorerProvider.GetNetwork(cryptoCode);
-            if (network == null)
+            if (cryptoCode == null)
```
Comment (bolatovumar) [inline BTCPayServer/Controllers/UIStoresController.LightningLike.cs:326]: Same reasons for changing this as everything above.

File: BTCPayServer/Controllers/UIStoresController.LightningLike.cs [hunk 4]
```diff
@@ -347,8 +355,7 @@ private async Task SetExistingValues(StoreData store, LightningNodeViewModel vm)
             vm.CanUseInternalNode = await CanUseInternalLightning();
             var lightning = GetExistingLightningSupportedPaymentMethod(vm.CryptoCode, store);
 
-            var lnSet = lightning != null;
-            if (lnSet)
+            if (lightning != null)
```
Comment (bolatovumar) [inline BTCPayServer/Controllers/UIStoresController.LightningLike.cs:358]: Same as above.

File: BTCPayServer/Controllers/UIStoresController.LightningLike.cs [hunk 5]
```diff
@@ -206,6 +207,13 @@ public async Task<IActionResult> LightningSettings(string storeId, string crypto
             var storeBlob = store.GetStoreBlob();
             var excludeFilters = storeBlob.GetExcludedPaymentMethods();
             var lightning = GetExistingLightningSupportedPaymentMethod(cryptoCode, store);
+            if (lightning == null) 
+            {
+                TempData[WellKnownTempData.ErrorMessage] = $"Need to connect to a Lightning node before adjusting its settings.";
```
Comment (dennisreimann) [inline BTCPayServer/Controllers/UIStoresController.LightningLike.cs:212]:
```suggestion
                TempData[WellKnownTempData.ErrorMessage] = $"You need to connect to a Lightning node before adjusting its settings.";
```

**Comment by dennisreimann** [comment]
utACK

File: BTCPayServer/Controllers/UIStoresController.LightningLike.cs (hunk 5 above)
Comment (bolatovumar) [reply BTCPayServer/Controllers/UIStoresController.LightningLike.cs]: @dennisreimann updated here: https://github.com/btcpayserver/btcpayserver/pull/3410/commits/b0769c8b1e78a16530753fdfbc37a2dd7d83b462

**Review by dennisreimann — APPROVED** [review]
tACK - up to @kukks and @NicolasDorier to decide if enabling `nullable` is good :)
