### PR TITLE
Webhooks: Fix invoice interpolation

### LINKED ISSUE #5584: (bug) interpolation broken for email placeholders in 1.12
After updating to 1.12, our email placeholder for Invoice.OrderId is not interpolating. Exact text below.

"Thank you for your purchase! Your payment for order #{Invoice.OrderId} is confirmed."

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes #5584.

### CODE REVIEW

File: BTCPayServer/HostedServices/Webhooks/InvoiceWebhookDeliveryRequest.cs [hunk 1]
```diff
@@ -46,7 +44,7 @@ private string Interpolate(string str)
             .Replace("{Invoice.OrderId}", Invoice.Metadata.OrderId);
 
 
-        res = InterpolateJsonField(str, "Invoice.Metadata", Invoice.Metadata.ToJObject());
+        res = InterpolateJsonField(res, "Invoice.Metadata", Invoice.Metadata.ToJObject());
```
Comment (dennisreimann) [inline BTCPayServer/HostedServices/Webhooks/InvoiceWebhookDeliveryRequest.cs:47]: Here's the fix.
