### PR TITLE
Adapt cookie auth to work with same API permission system

### LINKED ISSUE #3512: [`Roles`] Error 403 while `issue refund` as `Guest`
**Description:**
Guest users cannot access the refund page anymore.

**Steps to reproduce the reported bug:**
1. Go to any invoice under `/invoices/ID` as a Guest.
2. Click on `Issue Refund`.
3. See `403 - DENIED` page.

image

**Expected behavior:**

Instead of 403 error, a guest user could issue the refund and send the link to the customer in case of a partial paid invoices

image

**Environment:**
- BTCPay Server Version: ` v1.4.6.0`
- Deployment Method: Docker
- Browser: Chrome

### PR DESCRIPTION
**Pull request by Kukks**
fixes #3512 

This PR merges the approach of permissions used in greenfield with the cookie auth used on the website. This will allow us to build a similar experience of fine-grained permissions for users on a server and store level through custom roles and custom  store roles.

### CODE REVIEW

**Review by dennisreimann — APPROVED** [review]
tACK. @Kukks can you take one more look at ebd3a41eabe03a217bd725252e9de09e469c94fb to verify my changes?

**Comment by NicolasDorier** [comment]
@Kukks I refactored it, seems didnt' break anything:

Basically the same as you did before, but I better handle the `Unscoped` stuff that was confusing.
Also, I added a `store.HasPermission()` method, and use this for Greenfield as well.

The idea is that after we can modify its implementation easily, if we make new roles or custom roles.

File: BTCPayServer/Data/StoreDataExtensions.cs [hunk 1]
```diff
@@ -14,6 +16,33 @@ namespace BTCPayServer.Data
...
+        public static PermissionSet GetPermissionSet(this StoreData store)
+        {
+            ArgumentNullException.ThrowIfNull(store);
+            if (store.Role is null)
+                return new PermissionSet();
+            return new PermissionSet(store.Role == StoreRoles.Owner
+                        ? new[]
+                        {
+                        Permission.Create(Policies.CanModifyStoreSettings, store.Id),
+                        Permission.Create(Policies.CanTradeCustodianAccount, store.Id),
```
Comment (Kukks) [inline BTCPayServer/Data/StoreDataExtensions.cs:28]: Can we group all these custodian permissions under a parent `managecustodian` permission?

File: BTCPayServer/Security/CookieAuthorizationHandler.cs [hunk 2]
```diff
@@ -112,49 +113,49 @@ protected override async Task HandleRequirementAsync(AuthorizationHandlerContext
...
-            if (string.IsNullOrEmpty(storeId))
-                storeId = null;
-            if (storeId != null)
+            if (!string.IsNullOrEmpty(storeId))
             {
                 store = await _storeRepository.FindStore(storeId, userId);
             }
 
-            switch (requirement.Policy)
+            if (Policies.IsServerPolicy(policy) && isAdmin)
```
Comment (Kukks) [inline BTCPayServer/Security/CookieAuthorizationHandler.cs:132]: Note: we should change this and make it generic so that we can have custom roles that allow a subset of server permissions

File: BTCPayServer/Security/CookieAuthorizationHandler.cs [hunk 3]
```diff
@@ -112,49 +113,49 @@ protected override async Task HandleRequirementAsync(AuthorizationHandlerContext
...
-            if (storeId == null)
+            storeId ??= _httpContext.GetUserPrefsCookie()?.CurrentStoreId;
+
+            var policy = requirement.Policy;
+            bool requiredUnscoped = false;
+            if (policy.EndsWith(':'))
             {
-                storeId = _httpContext.GetUserPrefsCookie()?.CurrentStoreId;
+                policy = policy.Substring(0, policy.Length - 1);
+                requiredUnscoped = true;
```
Comment (Kukks) [inline BTCPayServer/Security/CookieAuthorizationHandler.cs:123]: I dont understand this var, is it named right?

File: BTCPayServer/Data/StoreDataExtensions.cs [hunk 4]
```diff
@@ -14,6 +16,33 @@ namespace BTCPayServer.Data
...
+                        Permission.Create(Policies.CanWithdrawFromCustodianAccounts, store.Id),
+                        Permission.Create(Policies.CanDepositToCustodianAccounts, store.Id)
+                        }
+                        : new[]
+                        {
+                        Permission.Create(Policies.CanViewStoreSettings, store.Id),
+                        Permission.Create(Policies.CanModifyInvoices, store.Id),
```
Comment (Kukks) [inline BTCPayServer/Data/StoreDataExtensions.cs:35]: Should a store guest be able to modify invoices, or only create them?

File: BTCPayServer/Data/StoreDataExtensions.cs (hunk 1 above)
Comment (NicolasDorier) [reply BTCPayServer/Data/StoreDataExtensions.cs:28]: I asked to @woutersamaey about it and he NACK'd it.

image

He may have a point, so in doubt I left this point in potential future PR.

File: BTCPayServer/Security/CookieAuthorizationHandler.cs (hunk 2 above)
Comment (NicolasDorier) [reply BTCPayServer/Security/CookieAuthorizationHandler.cs:132]: So the issue is that the `StoreRole` is a different concept from the ASP.NET Role. (where we only have a single one, Admin)
As such, abstracting it isn't easy or possible.

File: BTCPayServer/Security/CookieAuthorizationHandler.cs (hunk 3 above)
Comment (NicolasDorier) [reply BTCPayServer/Security/CookieAuthorizationHandler.cs:123]: Basically the `***Unscoped` policy means that we require that the user/api key has the full unscoped `***` permission, and not a scoped one on a store for example.

IMHO shouldn't have done this way, instead I should have added a different permission such as `btcpay.user.modifystores` rather than piggy bagging `btcpay.stores.modifystores`

File: BTCPayServer/Data/StoreDataExtensions.cs (hunk 4 above)
Comment (NicolasDorier) [reply BTCPayServer/Data/StoreDataExtensions.cs:35]: This keep the current behavior in the UI, where the Guest can change the status. (I think it makes sense, for example you want the Guest to be able to mark an invoice complete)

I will double check to make sure I didn't changed this behavior.

File: BTCPayServer/Security/CookieAuthorizationHandler.cs (hunk 2 above)
Comment (Kukks) [reply BTCPayServer/Security/CookieAuthorizationHandler.cs:132]: Ah yes, but we can apply permissions to both StoreRole and aspnet Roles later on

File: BTCPayServer/Data/StoreDataExtensions.cs (hunk 1 above)
Comment (Kukks) [reply BTCPayServer/Data/StoreDataExtensions.cs:28]: We already have that tree system for permissions. Im asking to create a parent permission "Manage Custodians" which has the others as sub policies

Comment (woutersamaey) [reply BTCPayServer/Data/StoreDataExtensions.cs:28]: "Manage Custodians" is meant for managing the accounts and config, not doing anything in the custodian account itself (like making a trade, desposit or withdrawal). At least, that was my intention.

Comment (woutersamaey) [reply BTCPayServer/Data/StoreDataExtensions.cs:28]: To present as a tree, I would suggest we do:
- Custodian Accounts (this is a new parent level)
- - Manage Custodian Accounts (add, edit, configure, remove), this is a rename of "Manage Custodians" to "Manage Custodian Accounts"
- - Deposit
- - WIthdraw
- - Trade

File: BTCPayServer/Data/StoreDataExtensions.cs (hunk 4 above)
Comment (NicolasDorier) [reply BTCPayServer/Data/StoreDataExtensions.cs:35]: I think they already can, by the API.

File: BTCPayServer/Data/StoreDataExtensions.cs (hunk 1 above)
Comment (NicolasDorier) [reply BTCPayServer/Data/StoreDataExtensions.cs:28]: I will leave this topic for another PR to keep this one focused.

File: BTCPayServer/Data/StoreDataExtensions.cs (hunk 4 above)
Comment (NicolasDorier) [reply BTCPayServer/Data/StoreDataExtensions.cs:35]: Confirmed, they already can. Actually the UI only need `CanViewInvoice`, so should change this in a future PR.

**Comment by Bryansadventure** [comment]
Will I be able to withdrawl these funds soon?

**Comment by NicolasDorier** [comment]
follow up on https://github.com/btcpayserver/btcpayserver/pull/4780
